### PR TITLE
Use English download badges in `README.md` and align the same height

### LINKED ISSUE #141: AppStore buttons in `README.md` are in German
The whole `README.md` is in English. Therefore, it's a bit confusing that the AppStore buttons for iOS and macOS are in German.

image

### PR DESCRIPTION
**Pull request by nilsreichardt**
## Before
image

## After
image

Using the official badges by Apple: https://developer.apple.com/app-store/marketing/guidelines/

## Related Tickets
Closes #141

### CODE REVIEW

**Comment by Jonas-Sander** [comment]
Aligning the height makes it look weird on mobile though:

Before


After

**Review by Jonas-Sander — CHANGES_REQUESTED** [review]
See above - can this be fixed?

**Comment by nilsreichardt** [comment]
After fixing:

image
(mobile)

image
(desktop)

The fix is to use `width` instead of `height`

**Review by Jonas-Sander — APPROVED** [review]
LGTM:)

**Pull request merged**
