### PR TITLE
Use `fvm` in GitHub Actions and Sharezone CLI.

### LINKED ISSUE #255: Sharezone CLI doesn't support (just) FVM
## Describe the bug
When installing just Flutter via `fvm` and not having Flutter set (`flutter` is not available) then errors occure when running commands that use flutter.

## Steps to reproduce the bug
1. Set up the `sharezone-app` repo
2. Set up `fvm`
3. Run `sz pub get`

## Current _broken_ behavior
The CLI should use `fvm` and only `flutter` if `fvm` is not available.

## Expected behavior
The CLI tries to use `flutter` and doesn't use `fvm`.

### PR DESCRIPTION
**Pull request by Jonas-Sander**
Instead of using `flutter` and `dart` we use `fvm flutter` and `fvm dart` in the CLI and GitHub Actions to ensure the same version of Flutter and Dart is used everywhere.

As a quick fix I just replaced the commands, if `fvm` is not installed this will fail instead of falling back to using just `flutter`/`dart`. We might add this fallback mechanism later if we really need it.

I tested this change via `sz test` and `sz analyze` locally.

Fixes #255

### CODE REVIEW

**Review by nilsreichardt — APPROVED** [review]
LGTM

**Comment by nilsreichardt** [comment]
We also need to install `fvm` in GitHub Actions

**Comment by nilsreichardt** [comment]
⬇️ Generated builds by [Codemagic](https://codemagic.io/app/629c82ea463af7ff553fc7a5/build/63bc3cddab26c4eee324a91a) for commit b44e34f7044522445f6d33042ca215045e8a856a ⬇️

_Note_: Only Sharezone team members are able to install the iOS app.

| iOS | Android |
|:-:|:-:|
| image <br /> [Download link](https://api.codemagic.io/artifacts/43d0a497-2c85-4f9a-8259-1dbbf9692dc6/83ccee58-bd3a-4d63-b134-76c389f69d76/sharezone.ipa) | image <br /> [Download link](https://api.codemagic.io/artifacts/30781866-dc2e-4d65-9e4c-a8a6f2878eca/a23a0488-d193-41e7-945b-345564bbc258/app-dev-release.apk) |

**Comment by Jonas-Sander** [comment]
@nilsreichardt The GitHub action jobs now use FVM as well. Can you review again?

**Review by nilsreichardt — APPROVED** [review]
LGTM

**Pull request merged**
