### PR TITLE
Upgrade to Flutter v3.24.2

### PR DESCRIPTION
**Pull request by nilsreichardt**
Migrations:
* [Generic types in PopScope](https://docs.flutter.dev/release/breaking-changes/popscope-with-result)
* [Deprecate `ButtonBar` in favor of `OverflowBar`](https://docs.flutter.dev/release/breaking-changes/deprecate-buttonbar)

### CODE REVIEW

**Comment by Sharezone-Admin** [comment]
⬇️ Builds generated by [Codemagic](https://codemagic.io) for commit 1d34a0a25f80cd6cd8898fd262b83c464ef929a3 ⬇️

_Note_: Only Sharezone team members are able to install the iOS app.

| iOS | | Android |
|:-:|:-:|:-:|
| iOS QR code <br /> [Download link](https://api.codemagic.io/artifacts/.eJwVx7mSgjAAANB_sWdGAoIUFgHCFQi3KA0DwqCsUYicfv3uvu7tWvhPpZNfW8DteH_Z8-JewefhE1JC6XJ4iw-96tfrk2-ZauMfy0phWyPj7kXIr8uE0YSWWu5H6x0Ubj-gB9EVl01EY16eKdm3x8OnRxURFMN-qulZzOVVZ18mmmwV4VwGc8wv-Jr1r1KVOJMcq4nS2XGA0wmLhNI6pxebSJlqG3E5h8WW3EDKZWYQZSKErrDJzHsOuHGPwDt3f2uPWNiq6BIk8gvJsSU3BwCwjJyNHxsC30GX2CgenbYItbKqxhuIXFsaluljChIpzHjaOIfQ6Cpx-wSeTrtf-IpgFA.yugf5nUmkNnHIghfk4UBhZZnXUE) | | Android QR code <br /> [Download link](https://api.codemagic.io/artifacts/.eJwVzEmSgjAAAMC_eE8VoiA5eMBIQFBZIiBeLBwkiYhsMiS-3pl-QM-o-W9Tj37h3NxeTHwRIOMh2hjcbUdTGG10kGG1bdiLKEOGklN4Mqu9AOlPYgGYb_1CYAKXl36SfKtQOPjqI4cyDSrJEVKzpwKplV7M8K-cxqF-HZmCp7LpG1SbS-eDcWjp893GG6I3FKDqPC84n6-A9hly6OCW_FB2iK3a2DKIuqLzmkQ59FnaBWd7Xi4vRiK7WzumkZDuwSruZHqS2CQhW2js866GodptclgksfbkoZ7XLsI1PxIpKdbkngf3W3HV4XbUODDt_Cpt4zdzIqEeX07ReNN6PfsCTcJieg.jjeAG4H-UHLWyENLrRG5D4ub_jY) |

<sub>(expires Tue, 10 Sep 2024 16:31:02 GMT)<br/>Codemagic build: [66b8e41399adaafd53736e74](https://codemagic.io/app/629c82ea463af7ff553fc7a5/build/66b8e41399adaafd53736e74); comment generated with [Codemagic App Preview](https://github.com/nilsreichardt/codemagic-app-preview)</sub>

**Comment by Jonas-Sander** [comment]
Can we hold off until https://github.com/NixOS/nixpkgs/issues/333197 is resolved? Because I tried for an hour to install flutter on my NixOS system and even with the old method of using fvm it doesn't work right now.

**Comment by nilsreichardt** [comment]
@Jonas-Sander Is this PR ready to merge now since https://github.com/NixOS/nixpkgs/issues/333197 is closed?

**Comment by Jonas-Sander** [comment]
> @Jonas-Sander Is this PR ready to merge now since [NixOS/nixpkgs#333197](https://github.com/NixOS/nixpkgs/issues/333197) is closed?

Well the nix version of flutter is now upgraded, but using this version lead me to this bug: https://github.com/flutter/flutter/issues/153238, which makes it unusable for me. If you want to upgrade, then we could merge the following PR, so that I just use the fvm version again: #1726

**Comment by nilsreichardt** [comment]
@Jonas-Sander Can you review the PR?

**Review by Jonas-Sander — APPROVED** [review]
LGTM

**Comment by Jonas-Sander** [comment]
This seems wrong:

image

**Comment by nilsreichardt** [comment]
> This seems wrong:
> 
> image

Thanks! Fixed ✅

**Pull request merged**
