### PR TITLE
Add `sz format` command.

### LINKED ISSUE #589: Add command to format code, like `sz format`
`sz format` formats our code with our formatting standards. At the moment, it's just `dart format .`

### PR DESCRIPTION
**Pull request by Jonas-Sander**
Closes #589

### CODE REVIEW

**Review by nilsreichardt — APPROVED** [review]
LGTM

(can we use `sz format` inside `sz analyze`?)

**Comment by Jonas-Sander** [comment]
> 

What do you mean exactly?

**Comment by nilsreichardt** [comment]
> What do you mean exactly?

My thought was that have now two places where we define how to format code, in `sz format` and `sz analyze`. When we change how we format code, we would need to update it at two places. But maybe this too overkill for now because I don't we going to update that often.

But maybe a comment above `return runProcessSucessfullyOrThrow('fvm', ['dart', 'format', '.'],` that if change this command, we also need to change it in `sz analyze`

**Comment by Jonas-Sander** [comment]
> > What do you mean exactly?
> 
> My thought was that have now two places where we define how to format code, in `sz format` and `sz analyze`. When we change how we format code, we would need to update it at two places. But maybe this too overkill for now because I don't we going to update that often.
> 
> But maybe a comment above `return runProcessSucessfullyOrThrow('fvm', ['dart', 'format', '.'],` that if change this command, we also need to change it in `sz analyze`, would be good

I'm just gonna let both use one format method with an argument, after both PRs have been merged 👍

**Pull request merged**
