### PR TITLE
Licence check ignore generated dart files

### PR DESCRIPTION
**Pull request by Jonas-Sander**

### CODE REVIEW

**Comment by nilsreichardt** [comment]
FYI: The app preview check is failing because the GitHub API changed (I think) and I need to fix this in the package

**Review by nilsreichardt — APPROVED** [review]
LGTM

Would be great to add this command to the Sharezone CLI in the future because when add later more file types to ignore, we can just this command.

For FlutterFire I have added a Melos command (`melos run add-license-header`): https://github.com/firebase/flutterfire/blob/08a4be6c0e86a3288bb6fcafd301f1519b7915ba/melos.yaml#L266

**Comment by Jonas-Sander** [comment]
> LGTM
> 
> Would be great to add this command to the Sharezone CLI in the future because when add later more file types to ignore, we can just this command.
> 
> For FlutterFire I have added a Melos command (`melos run add-license-header`): https://github.com/firebase/flutterfire/blob/08a4be6c0e86a3288bb6fcafd301f1519b7915ba/melos.yaml#L266

https://github.com/SharezoneApp/sharezone-app/issues/326

**Comment by Jonas-Sander** [comment]
> FYI: The app preview check is failing because the GitHub API changed (I think) and I need to fix this in the package

Do you have time to do this? Else all test runs for all the PRs will fail in the future, won't they?

**Comment by Jonas-Sander** [comment]
> FYI: The app preview check is failing because the GitHub API changed (I think) and I need to fix this in the package

@nilsreichardt Should I merge this anyways or wait until the action is fixed? Don't really like to have `main` failing as well.

**Comment by nilsreichardt** [comment]
> @nilsreichardt Should I merge this anyways or wait until the action is fixed? Don't really like to have main failing as well.

When you don't need the changes in this month then you keep open the PR because I might fix this in the month. However, I'm okay with merging it now

**Comment by nilsreichardt** [comment]
⬇️ Generated builds by [Codemagic](https://codemagic.io/app/629c82ea463af7ff553fc7a5/build/63b83ebb874a727166ee7236) for commit 639173613797dad501d803b6b0c81e1d8ad3e0bb ⬇️

_Note_: Only Sharezone team members are able to install the iOS app.

| iOS | Android |
|:-:|:-:|
| image <br /> [Download link](https://api.codemagic.io/artifacts/0256b4c9-4d2e-43f3-a2fc-b0a98ff8f924/6992a4db-7663-4a1e-8d05-667e0b9130f8/sharezone.ipa) | image <br /> [Download link](https://api.codemagic.io/artifacts/9efdc6e9-fb05-4d31-b3e5-b3903c9b6c88/c562108b-9979-453d-9e49-cce128fe8ece/app-dev-release.apk) |

**Pull request merged**
