### PR TITLE
Assign label "dependencies" automatically

### PR DESCRIPTION
**Pull request by nilsreichardt**

### CODE REVIEW

**Comment by Jonas-Sander** [comment]
But we're importing all our `/lib` packages there as well?

**Comment by nilsreichardt** [comment]
> But we're importing all our `/lib` packages there as well?

It's intended when a dependency changes in `lib` that it should get the label. Not sure if "**external** dependency" is maybe a bit misleading and just "dependencies" is better, because a PR should also get the label when `app` imports an internal package

**Comment by Jonas-Sander** [comment]
Okay then I understood it wrong, then change it back to just dependencies if you want, sry

**Review by Jonas-Sander — APPROVED** [review]

**Comment by nilsreichardt** [comment]
I also forgot about this case in the PR 😅

**Pull request merged**
