### PR TITLE
Replace `open_file` package with `open_file_plus`.

### PR DESCRIPTION
**Pull request by Jonas-Sander**
Fixes Android permission errors that come up on >= Android 11: `Permission denied: android.Manifest.permission.MANAGE_EXTERNAL_STORAGE`.

Note: I only tested this works on Android 11, not earlier versions.

### CODE REVIEW

**Comment by Jonas-Sander** [comment]
Hm idk why the file diffs look so weird, did the line endings change because I'm on Windows maybe? But I made several PRs from Windows and this hasn't happend before 🤔

**Comment by Jonas-Sander** [comment]
> Hm idk why the file diffs look so weird, did the line endings change because I'm on Windows maybe? But I made several PRs from Windows and this hasn't happend before 🤔

Hm, fixed it now by running `git config --global core.autocrlf true` and `git add --renormalize [file_path]` for the affected files.

**Comment by nilsreichardt** [comment]
> _getFilePathWithLowerCaseExtension

Yes, I'm opened #637

**Review by nilsreichardt — APPROVED** [review]
LGTM

I have successfully tested it with Android 13 and macOS. On Android 5 (I used an emulator) it opened the app to view the file on the phone. However, this app couldn't the image. Not sure if this an issue caused by the package or just an issue with the Android emulator. I would just merge it for now 👍

**Pull request merged**
