### PR TITLE
Replace `CrashAnalyticsBloc` with Provider<CrashAnalytics>.

### PR DESCRIPTION
**Pull request by Jonas-Sander**

### CODE REVIEW

**Comment by nilsreichardt** [comment]
⬇️ Generated builds by [Codemagic](https://codemagic.io/app/629c82ea463af7ff553fc7a5/build/63bf0bf5c1842e1525a4e338) for commit 731c826b26aea2f5bc8c7473fa1ef0b54cbe5235 ⬇️

_Note_: Only Sharezone team members are able to install the iOS app.

| iOS | Android |
|:-:|:-:|
| image <br /> [Download link](https://api.codemagic.io/artifacts/0ca5e56d-22e0-4e2c-949a-655134231b1b/bfd55a56-25e5-4578-929e-05ee940c1c8e/sharezone.ipa) | image <br /> [Download link](https://api.codemagic.io/artifacts/ace891c3-def4-4e36-b41d-7a66d2009806/a23af6fa-663c-4379-9e52-739732fff66e/app-dev-release.apk) |

**Comment by Jonas-Sander** [comment]
> ⬇️ Generated builds by [Codemagic](https://codemagic.io/app/629c82ea463af7ff553fc7a5/build/63bf0bf5c1842e1525a4e338) for commit [731c826](https://github.com/SharezoneApp/sharezone-app/commit/731c826b26aea2f5bc8c7473fa1ef0b54cbe5235) 

@nilsreichardt Btw, why are these comments posted by ur account and not @Sharezone-Admin ?

**Comment by nilsreichardt** [comment]
> @nilsreichardt Btw, why are these comments posted by ur account and not @Sharezone-Admin ?

Yes, this make more sense 👍 I created a ticket for this: #335

**Review by nilsreichardt — APPROVED** [review]
LGTM

**Pull request merged**
