### PR TITLE
Disable concurrency for `sz` command in our CI/CD pipeline

### LINKED ISSUE #1658: CI/CD pipelines fails because of "Another git process seems to be running in this repository"
```
ProcessRunnerException: Running "flutter test --test-randomize-ordering-seed 4010264459 --dart-define=TEST_RANDOMNESS_SEED=4010264459" in /home/runner/work/sharezone-app/sharezone-app/lib/last_online_reporting exited with code 69
Resolving dependencies...
Downloading packages...
Git error. Command: `git checkout 2f680bb80119f6fd037a7bda0984bc811b5dccb8`
stdout: 
stderr: fatal: Unable to create '/home/runner/.pub-cache/git/packages-2f680bb80119f6fd037a7bda0984bc811b5dccb8/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
exit code: 1[28](https://github.com/SharezoneApp/sharezone-app/actions/runs/9436357917/job/25990962362#step:7:29)
:
Git error. Command: `git checkout 2f680bb80119f6fd037a7bda0984bc811b5dccb8`
stdout: 
stderr: fatal: Unable to create '/home/runner/.pub-cache/git/packages-2f680bb80119f6fd037a7bda0984bc811b5dccb8/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
exit code: 128
```

### PR DESCRIPTION
**Pull request by nilsreichardt**
Not sure if there is another easy way to fix #1658

### CODE REVIEW

**Review by Jonas-Sander — APPROVED** [review]

**Comment by nilsreichardt** [comment]
It still doesn't fix the issue: https://github.com/SharezoneApp/sharezone-app/actions/runs/9437120612/job/25992640142?pr=1659

**Comment by nilsreichardt** [comment]
image

Do you know why still 5 packages are processed concurrent while using `--max-concurrent-packages 1`? https://github.com/SharezoneApp/sharezone-app/actions/runs/9437120612/job/25992640142?pr=1659

**Comment by Jonas-Sander** [comment]
> image
> 
> @Jonas-Sander Do you know why still 5 packages are processed concurrent while using `--max-concurrent-packages 1`? https://github.com/SharezoneApp/sharezone-app/actions/runs/9437120612/job/25992640142?pr=1659

No, it works locally like it should. I'm gonna play around with it in this PR.

**Comment by Jonas-Sander** [comment]
@nilsreichardt putting it into one line works.

So instead of
```
        run: sz analyze \
          --max-concurrent-packages 1 \
          --package-timeout-minutes 15
```
it works like this
```
        run: sz analyze --max-concurrent-packages 1 --package-timeout-minutes 15
```

**Comment by nilsreichardt** [comment]
Ah the | at the beginning is missing 😭

**Pull request merged**
