### PR TITLE
Upgrade to Flutter v2.10.5

### PR DESCRIPTION
**Pull request by nilsreichardt**
* Changed version in `.fvm/fvm_config.json`
* Fix all analyzer warnings

## ToDo
* [x] Check builds for all platforms

### CODE REVIEW

**Comment by Jonas-Sander** [comment]
Before merging we should ensure that it still builds and works for at least iOS, Android and Web. Past upgrades sometimes broke the build for some platforms I think.

**Comment by Jonas-Sander** [comment]
Also see if there is anything that applies to us: https://docs.flutter.dev/release/breaking-changes#released-in-flutter-25

**Comment by nilsreichardt** [comment]
> Before merging we should ensure that it still builds and works for at least iOS, Android and Web. Past upgrades sometimes broke the build for some platforms I think.

Yeah, I'll do this. When we have integration tests (hopefully for all platforms), we will have this step in our CI integrated 💪

**Comment by nilsreichardt** [comment]
telegram-cloud-photo-size-2-5418116255270943730-y

lol, since the Flutter update got the overview page in the mobile view a different styling xD I think we should later also add screenshot tests for the every page to avoid errors like this (should be done with integration test package).

**Comment by Jonas-Sander** [comment]
image

**Comment by Jonas-Sander** [comment]
image

**Comment by Jonas-Sander** [comment]
image

**Comment by nilsreichardt** [comment]
iOS builds are working again :)

**Comment by nilsreichardt** [comment]
@Jonas-Sander You can review again :)

**Comment by nilsreichardt** [comment]
Seems so that there are still some UI elements not adjusted for the dark mode. But I just saw that they don't have anything to with the 2.10.5 upgrade because they already in https://web.sharezone.net app. I created the issues: #167, #168, #169

**Review by Jonas-Sander — APPROVED** [review]
LGTM

**Pull request merged**
